[[headers]]
for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"
  Timing-Allow-Origin = "*"

[[headers]]
for = "/css/*"
  [headers.values]
  Cache-Control = "public, max-age=86400"
  Access-Control-Allow-Origin = "*"


