/**
 * Dynamic CSS endpoint to emulate Google Fonts-style usage:
 *   /api/fonts.css?family=I+Love+You&family=College+Black&display=swap
 *
 * Returns @font-face rules pointing to files in /fonts.
 * Notes:
 * - We serve .otf only (format("opentype")) in this repo
 * - Unknown families are ignored
 */

/** @type {import('http').ServerResponse} */

const FAMILY_MAP = (() => {
  /** Normalize key for lookup */
  const key = (name) => name.trim().toLowerCase();
  const map = new Map();

  /** Helper to add a family */
  function add(family, file, weight = 400, style = 'normal') {
    const k = key(family);
    if (!map.has(k)) map.set(k, { family, variants: [] });
    map.get(k).variants.push({ file, weight, style });
  }

  // Known fonts in /fonts (WOFF format)
  add('I Love You', 'ILoveYou-Regular.woff');
  add('Bubble Note', 'BubbleNoteRegular.woff');
  add('Cheery Note', 'CheeryNoteRegular.woff');
  add('Cute Charm', 'CuteCharmRegular.woff');
  add('Glee Script', 'GleeScriptRegular.woff');
  add('Happy Hand', 'HappyHandRegular.woff');
  add('Jolly Scriptble', 'JollyScriptbleRegular.woff');
  add('Lovely Letter', 'LovelyLetterRegular.woff');
  add('Playful Pen', 'PlayfulPenRegular.woff');
  add('Poppy Line', 'PoppyLineRegular.woff');
  add('Smiley Script', 'SmileyScriptRegular.woff');
  add('Sunny Sketch', 'SunnySketchRegular.woff');
  add('Whimsy Wonder', 'WhimsyWonderRegular.woff');
  add('College Black', 'CollegeBlackRegular.woff', 900);
  add('Chicago Athletic', 'ChicagoAthletic-Script1.woff');
  add('Chicago Athletic', 'ChicagoAthletic-Script2.woff');
  add('Chicago Athletic', 'ChicagoAthletic-SlabSerif1.woff');
  add('Chicago Athletic', 'ChicagoAthletic-SlabSerif2.woff');
  add('Retro Vintage', 'RetroVintageRegular.woff');
  add('Simple Stacked', 'SimpleStackedRegular.woff');
  add('Triple Rainbow', 'TripleRainbowRegular.woff');
  add('Grinch Wave', 'GrinchWave.woff');
  add('Wicked Halloween', 'WickedHalloweenRegular.woff');
  // Heart Style families
  add('Heart Style - Tail', 'HeartStyleTail.woff');
  add('Heart Style - Tail Heart', 'HeartStyleTailHeart.woff');
  add('Heart Style - Heart', 'HeartStyleHeart.woff');
  add('Heart Style', 'HeartStyle.woff');
  add('Benefit', 'BenefitRegular.woff');

  return map;
})();

function decodeFamilyParam(value) {
  // Google Fonts style: spaces as '+', optional axis like ":wght@700;900"
  const cleaned = value.replace(/\+/g, ' ');
  const [name] = cleaned.split(':');
  try {
    return decodeURIComponent(name);
  } catch {
    return name;
  }
}

function toCss(display, families) {
  let css = '/* Generated by /api/fonts.css */\n';
  for (const fam of families) {
    for (const v of fam.variants) {
      const filePath = '/fonts/' + encodeURIComponent(v.file).replace(/%2520/g, '%20');
      const format = v.file.endsWith('.woff') ? 'woff' : 'woff2';
      css += `@font-face{font-family:"${fam.family}";src:url("${filePath}") format("${format}");font-weight:${v.weight};font-style:${v.style};font-display:${display};}\n`;
    }
  }
  return css;
}

export default function handler(req, res) {
  const { family, display } = req.query;
  const fontDisplay = typeof display === 'string' && display ? display : 'swap';

  const requested = Array.isArray(family)
    ? family.filter(Boolean)
    : family
    ? [family]
    : [];

  const selected = [];
  if (requested.length === 0) {
    // No family specified → return all families
    for (const [, value] of FAMILY_MAP) selected.push(value);
  } else {
    for (const raw of requested) {
      const name = decodeFamilyParam(raw);
      const found = FAMILY_MAP.get(name.trim().toLowerCase());
      if (found) selected.push(found);
    }
  }

  const css = toCss(fontDisplay, selected);

  res.setHeader('Content-Type', 'text/css; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.status(200).send(css);
}


